-- require("luca.plugins-setup")
-- require("luca.core.options")
-- require("luca.core.keymaps")
-- require("luca.core.colorscheme")
-- require("luca.plugins.comment")
-- require("luca.plugins.nvim-tree")
-- require("luca.plugins.lualine")
-- require("luca.plugins.telescope")
-- require("luca.plugins.nvim-cmp")
-- require("luca.plugins.lsp.mason")
-- require("luca.plugins.lsp.lspsaga")
-- require("luca.plugins.lsp.lspconfig")
-- require("luca.plugins.lsp.null-ls")
-- require("luca.plugins.autopairs")
-- require("luca.plugins.treesitter")
-- require("luca.plugins.gitsigns")
-- require("luca.plugins.ouroboros")
-- require("luca.plugins.cppswitch")

-- lazy version (will become it)
require("core.options")
require("core.keymaps")
require("config.lazy")
